version: "3"
services:
  app:
    image: ruby:2.6.6
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    environment:
      - BUNDLE_APP_CONFIG=/app/.bundle
    user: "${UID}:${GID}"
    ports:
      - 3100:3000
